2025-06-16 19:58:10,413	WARNING utils.py:594 -- Detecting docker specified CPUs. In previous versions of Ray, CPU detection in containers was incorrect. Please ensure that Ray has enough CPUs allocated. As a temporary workaround to revert to the prior behavior, set `RAY_USE_MULTIPROCESSING_CPU_COUNT=1` as an env var before starting Ray. Set the env var: `RAY_DISABLE_DOCKER_CPU_WARNING=1` to mute this warning.
2025-06-16 19:58:11,636	INFO worker.py:1832 -- Started a local Ray instance. View the dashboard at [1m[32mhttp://127.0.0.1:8265 [39m[22m
INFO:nemo_rl.distributed.virtual_cluster:Started local cluster with tag 'nrl_tag_0': {'node:__internal_head__': 1.0, 'nrl_tag_0': 1.0, 'CPU': 16.0, 'memory': 1951704554496.0, 'object_store_memory': 200000000000.0, 'GPU': 1.0, 'node:10.65.27.31': 1.0, 'accelerator_type:H100': 1.0}
Map:   0%|          | 0/620 [00:00<?, ? examples/s]Map: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 620/620 [00:00<00:00, 5952.36 examples/s]Map: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 620/620 [00:00<00:00, 5718.60 examples/s]
INFO:nemo_rl.utils.venvs:NEMO_RL_VENV_DIR is set to /lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs.
Using CPython 3.12.9 interpreter at: /home/ray/anaconda3/bin/python3
Creating virtual environment at: venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker
warning: `VIRTUAL_ENV=.venv` does not match the project environment path `venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker` and will be ignored; use `--active` to target the active environment instead
Resolved 313 packages in 12ms
warning: Failed to uninstall package at venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/blake3-1.0.5.dist-info due to missing `RECORD` file. Installation may result in an incomplete environment.
warning: Failed to uninstall package at venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/pillow-11.2.1.dist-info due to missing `RECORD` file. Installation may result in an incomplete environment.
Uninstalled 73 packages in 3.96s
 - airportsdata==20250523
 - anyio==4.9.0
 - astor==0.8.1
 - blake3==1.0.5
 - cloudpickle==3.1.1
 - compressed-tensors==0.9.3
 - cupy-cuda12x==13.4.1
 - deprecated==1.2.18
 - depyf==0.18.0
 - diskcache==5.6.3
 - distro==1.9.0
 - dnspython==2.7.0
 - email-validator==2.2.0
 - fastapi==0.115.12
 - fastapi-cli==0.0.7
 - fastrlock==0.8.3
 - gguf==0.16.3
 - h11==0.16.0
 - httpcore==1.0.9
 - httptools==0.6.4
 - httpx==0.28.1
 - importlib-metadata==8.0.0
 - interegular==0.3.3
 - jiter==0.10.0
 - lark==1.2.2
 - llguidance==0.7.24
 - llvmlite==0.44.0
 - lm-format-enforcer==0.10.11
 - mistral-common==1.5.6
 - msgspec==0.19.0
 - nest-asyncio==1.6.0
 - ninja==1.11.1.4
 - numba==0.61.2
 - openai==1.82.0
 - opencv-python-headless==4.11.0.86
 - opentelemetry-api==1.26.0
 - opentelemetry-exporter-otlp==1.26.0
 - opentelemetry-exporter-otlp-proto-common==1.26.0
 - opentelemetry-exporter-otlp-proto-grpc==1.26.0
 - opentelemetry-exporter-otlp-proto-http==1.26.0
 - opentelemetry-proto==1.26.0
 - opentelemetry-sdk==1.26.0
 - opentelemetry-semantic-conventions==0.47b0
 - opentelemetry-semantic-conventions-ai==0.4.9
 - outlines==0.1.11
 - outlines-core==0.1.26
 - partial-json-parser==0.2.1.1.post5
 - pillow==11.2.1
 - prometheus-fastapi-instrumentator==7.1.0
 - py-cpuinfo==9.0.0
 - pycountry==24.6.1
 - python-dotenv==1.1.0
 - python-json-logger==3.3.0
 - python-multipart==0.0.20
 - pyzmq==26.4.0
 - rich-toolkit==0.14.6
 - scipy==1.15.3
 - sentencepiece==0.2.0
 - shellingham==1.5.4
 - sniffio==1.3.1
 - starlette==0.46.2
 - tiktoken==0.9.0
 - torchaudio==2.6.0
 - torchvision==0.21.0
 - typer==0.16.0
 - uvicorn==0.34.2
 - uvloop==0.21.0
 - vllm==0.8.5
 - watchfiles==1.0.5
 - websockets==15.0.1
 - xformers==0.0.29.post2
 - xgrammar==0.1.18
 - zipp==3.22.0
warning: `VIRTUAL_ENV=.venv` does not match the project environment path `venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker` and will be ignored; use `--active` to target the active environment instead
Installed 71 packages in 4.52s
Traceback (most recent call last):
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/examples/run_eval_genrm.py", line 409, in <module>
    main()
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/examples/run_eval_genrm.py", line 394, in main
    vllm_generation = VllmGeneration(cluster=cluster, config=config["generation"])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/nemo_rl/models/generation/vllm.py", line 987, in __init__
    self.device_uuids = self._report_device_id()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/nemo_rl/models/generation/vllm.py", line 1117, in _report_device_id
    results = ray.get(futures)
              ^^^^^^^^^^^^^^^^
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/.venv/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/.venv/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/.venv/lib/python3.12/site-packages/ray/_private/worker.py", line 2771, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/.venv/lib/python3.12/site-packages/ray/_private/worker.py", line 921, in get_objects
    raise value
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, [36mray::vllm_policy-0-0:VllmGenerationWorker.__init__()[39m (pid=2179840, ip=10.65.27.31, actor_id=22c055e4201046d8331baca201000000, repr=VllmGenerationWorker)
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/__init__.py", line 12, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 18, in <module>
    from vllm.config import (BlockSize, CacheConfig, CacheDType, CompilationConfig,
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/config.py", line 30, in <module>
    from vllm.model_executor.layers.quantization import (QUANTIZATION_METHODS,
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/model_executor/__init__.py", line 5, in <module>
    from vllm.model_executor.sampling_metadata import (SamplingMetadata,
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/model_executor/sampling_metadata.py", line 10, in <module>
    from vllm.sequence import (VLLM_TOKEN_ID_ARRAY_TYPE, SequenceData,
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/sequence.py", line 19, in <module>
    from vllm.multimodal import MultiModalKwargs, MultiModalPlaceholderDict
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/multimodal/__init__.py", line 2, in <module>
    from .base import MultiModalPlaceholderMap
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/multimodal/base.py", line 11, in <module>
    from .inputs import MultiModalKwargs, PlaceholderRange
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/multimodal/inputs.py", line 15, in <module>
    from PIL.Image import Image
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

[36mray::vllm_policy-0-0:VllmGenerationWorker.__init__()[39m (pid=2179840, ip=10.65.27.31, actor_id=22c055e4201046d8331baca201000000, repr=VllmGenerationWorker)
  File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/nemo_rl/models/generation/vllm.py", line 190, in __init__
    raise ImportError(
ImportError: vLLM is not installed. Please check that the py_executable in the runtime_env of VllmGenerationWorker covers the vllm dependency. You may have to update nemo_rl/distributed/ray_actor_environment_registry.py. If you are working interactively, you can install by running  `uv sync --extra vllm` anywhere in the repo.
[36m(VllmGenerationWorker pid=2179840)[0m Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::vllm_policy-0-0:VllmGenerationWorker.__init__()[39m (pid=2179840, ip=10.65.27.31, actor_id=22c055e4201046d8331baca201000000, repr=VllmGenerationWorker)
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/__init__.py", line 12, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 18, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from vllm.config import (BlockSize, CacheConfig, CacheDType, CompilationConfig,
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/config.py", line 30, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from vllm.model_executor.layers.quantization import (QUANTIZATION_METHODS,
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/model_executor/__init__.py", line 5, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from vllm.model_executor.sampling_metadata import (SamplingMetadata,
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/model_executor/sampling_metadata.py", line 10, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from vllm.sequence import (VLLM_TOKEN_ID_ARRAY_TYPE, SequenceData,
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/sequence.py", line 19, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from vllm.multimodal import MultiModalKwargs, MultiModalPlaceholderDict
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/multimodal/__init__.py", line 2, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from .base import MultiModalPlaceholderMap
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/multimodal/base.py", line 11, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from .inputs import MultiModalKwargs, PlaceholderRange
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/venvs/nemo_rl.models.generation.vllm.VllmGenerationWorker/lib/python3.12/site-packages/vllm/multimodal/inputs.py", line 15, in <module>
[36m(VllmGenerationWorker pid=2179840)[0m     from PIL.Image import Image
[36m(VllmGenerationWorker pid=2179840)[0m ModuleNotFoundError: No module named 'PIL'
[36m(VllmGenerationWorker pid=2179840)[0m 
[36m(VllmGenerationWorker pid=2179840)[0m During handling of the above exception, another exception occurred:
[36m(VllmGenerationWorker pid=2179840)[0m 
[36m(VllmGenerationWorker pid=2179840)[0m [36mray::vllm_policy-0-0:VllmGenerationWorker.__init__()[39m (pid=2179840, ip=10.65.27.31, actor_id=22c055e4201046d8331baca201000000, repr=VllmGenerationWorker)
[36m(VllmGenerationWorker pid=2179840)[0m   File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 456, in result
[36m(VllmGenerationWorker pid=2179840)[0m     return self.__get_result()
[36m(VllmGenerationWorker pid=2179840)[0m            ^^^^^^^^^^^^^^^^^^^
[36m(VllmGenerationWorker pid=2179840)[0m   File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
[36m(VllmGenerationWorker pid=2179840)[0m     raise self._exception
[36m(VllmGenerationWorker pid=2179840)[0m            ^^^^^^^^^^^^^^^^^^^^^
[36m(VllmGenerationWorker pid=2179840)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(VllmGenerationWorker pid=2179840)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(VllmGenerationWorker pid=2179840)[0m   File "/lustre/fsw/portfolios/llmservice/users/yizhuj/NeMo-RL/nemo_rl/models/generation/vllm.py", line 190, in __init__
[36m(VllmGenerationWorker pid=2179840)[0m     raise ImportError(
[36m(VllmGenerationWorker pid=2179840)[0m ImportError: vLLM is not installed. Please check that the py_executable in the runtime_env of VllmGenerationWorker covers the vllm dependency. You may have to update nemo_rl/distributed/ray_actor_environment_registry.py. If you are working interactively, you can install by running  `uv sync --extra vllm` anywhere in the repo.
